[base]
buildSystem = "cmake"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/arpack/"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/arpack/"
installDir = "/tmp/easifem/go-cli/install/extpkgs/arpack/"
git = 'github.com/easifem/base.git'
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
usePresent = true
libName = "easifemBase"
targetName = "easifemBase"
projectName = "easifemBase"

intSize = 32 # Default integer size
realSize = 64 # default real size
maxNNE = 128 # maximum number of nodes in an element to consider 
maxNodeToNode = 128 # maximum number of node to nodes.
maxNodeToElem = 128 # maximum number of node to element.

runtest = true
license = "GPL3"
buildOptions = [
"-D MPI:BOOL=OFF",
"-D ICB:BOOL=OFF",
"-D EIGEN:BOOL=OFF",
"-D EXAMPLES:BOOL=OFF"]
extpkgs = ["openblas", "openmp", "superlu", "lis", "hdf5", "plplot", "gmsh", "fftw", "gtkFortran", 
"lua"]

