envName="env1"

[env1]
quiet = true
buildDir = "/tmp/easifem/go-cli/build/"
installDir= "/tmp/easifem/go-cli/install/"
sourceDir= "/tmp/easifem/go-cli/src"
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true

[env2]
quiet = false
buildDir = "koko"
installDir= "soko"
sourceDir= "doko"
extpkgs = ["sparsekit"]


[install.md2src]
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/md2src/"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/md2src/"
installDir = "/tmp/easifem/go-cli/install/extpkgs/md2src/"
git = "github.com/easifem/md2src"
buildOptions = ["-D CMAKE_BUILD_TYPE:STRING=Release",
  "-D BUILD_SHARED_LIBS:BOOL=ON"
]

[install.sparsekit]
buildSystem = "cmake"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/sparsekit/"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/sparsekit/"
installDir = "/tmp/easifem/go-cli/install/extpkgs/sparsekit/"
git = "github.com/easifem/sparsekit"
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
libName = "Sparsekit"
runtest = true
license = "GPL3"
buildOptions = [""]

[install.lapack95]
buildSystem = "cmake"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/lapack95/"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/lapack95/"
installDir = "/tmp/easifem/go-cli/install/extpkgs/lapack95/"
git = "github.com/easifem/lapack95"
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
libName = "LAPACK95"
runtest = true
license = "GPL3"

[install.fftw]
buildSystem = "cmake"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/fftw/"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/fftw/"
installDir = "/tmp/easifem/go-cli/install/extpkgs/fftw/"
git = "github.com/easifem/fftw"
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
libName = "fftw"
runtest = true
license = "GPL3"
buildOptions = ["-D BUILD_TESTS:BOOL=ON",
"-D ENABLE_OPENMP:BOOL=ON",
"-D ENABLE_THREADS:BOOL=ON",
"-D WITH_COMBINED_THREADS:BOOL=OFF",
"-D ENABLE_FLOAT:BOOL=OFF",
"-D ENABLE_LONG_DOUBLE:BOOL=OFF",
"-D ENABLE_QUAD_PRECISION:BOOL=OFF",
"-D ENABLE_SSE:BOOL=OFF",
"-D ENABLE_SSE2:BOOL=OFF",
"-D ENABLE_AVX:BOOL=OFF",
"-D ENABLE_AVX2:BOOL=OFF",
"-D DISABLE_FORTRAN:BOOL=OFF",
]

[install.superlu]
buildSystem = "cmake"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/superlu/"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/superlu/"
installDir = "/tmp/easifem/go-cli/install/extpkgs/superlu/"
git = "github.com/easifem/superlu/"
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = false
libName = "superlu"
runtest = true
license = "GPL3"
buildOptions = [
"-D TPL_ENABLE_METISLIB:BOOL=OFF",
"-D enable_single:BOOL=ON",
"-D enable_double:BOOL=ON",
"-D enable_complex:BOOL=ON",
"-D enable_complex16:BOOL=ON",
"-D enable_matlabmex:BOOL=OFF",
"-D enable_doc:BOOL=OFF",
"-D enable_examples:BOOL=OFF",
"-D enable_tests:BOOL=ON"]

[install.arpack]
buildSystem = "cmake"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/arpack/"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/arpack/"
installDir = "/tmp/easifem/go-cli/install/extpkgs/arpack/"
git = 'github.com/easifem/arpack.git'
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
libName = "arpack"
runtest = true
license = "GPL3"
buildOptions = [
"-D MPI:BOOL=OFF",
"-D ICB:BOOL=OFF",
"-D EIGEN:BOOL=OFF",
"-D EXAMPLES:BOOL=OFF"]

[install.tomlf]
buildSystem = "cmake"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/toml-f"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/toml-f"
installDir = "/tmp/easifem/go-cli/install/extpkgs/toml-f"
git = 'github.com/toml-f/toml-f/'
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
libName = "tomlf"
runtest = true
license = "GPL3"
buildOptions = [""]

[install.lis]
buildSystem = "make"
sourceDir = "/tmp/easifem/go-cli/src/extpkgs/lis"
buildDir = "/tmp/easifem/go-cli/build/extpkgs/lis"
installDir = "/tmp/easifem/go-cli/install/extpkgs/lis"
git = 'github.com/easifem/lis/'
buildType = "Release" # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
libName = "lis"
runtest = true
license = "GPL3"
buildOptions = ["--enable-omp", "--enable-f90", "--enable-shared", "--enable-saamg"]
# env = ["CC=gcc-13"]
